encoder.emb.weight:
  start_epoch: 2
  end_epoch: 8
  ramp_epoch: 3
  freq: 50
  q: 0.1
  ramp_slope_mult: 2
encoder.rnn.weight_ih_l0:
  start_epoch: 2
  end_epoch: 8
  ramp_epoch: 3
  freq: 50
  q: 0.1
  ramp_slope_mult: 2
encoder.rnn.weight_hh_l0:
  start_epoch: 2
  end_epoch: 8
  ramp_epoch: 3
  freq: 50
  q: 0.1
  ramp_slope_mult: 2
decoder.lin.weight:
  start_epoch: 2
  end_epoch: 9
  ramp_epoch: 3
  freq: 50
  q: 0.15
  ramp_slope_mult: 2.5
